### ISSUE TITLE
タイムアウト時のメッセージ

### ISSUE THREAD

**Issue by takeshitou** [2016chubachi/tabitomo#113]
@aprisun 
マイクさん
タイムアウトの時、「true」のメッセージが表示されてました。

> 一定時間が経過したため、再度ログインが必要です`
> true

**Comment by aprisun** [comment]
唐さんが下記のコードで解決。

<ul>
        <% flash.each do |key, message| %>
          <% next if key == 'timedout'%>
          <li><%= message %></li>
        <% end %>
      </ul>
