### ISSUE TITLE
写真の枠が崩れる。

### ISSUE THREAD

**Issue by aprisun** [2016chubachi/tabitomo#184]
chrome だと枠が崩れる。
![screen shot 2016-12-17 at 20 26 45](https://cloud.githubusercontent.com/assets/9713934/21286558/b636b3f4-c49a-11e6-8a11-7f5b1790b3a9.png)

**Comment by takeshitou** [comment]
対応できたと思う、確認してね

**Comment by aprisun** [comment]
確認済み
