### ISSUE TITLE
メンバー登録すると「再度ログイン」が必要ですと表示される

### ISSUE THREAD

**Issue by yamamotoAIIT** [2016chubachi/tabitomo#202]
@aprisun さん　調査お願いします
メンバー登録すると
「一定時間が経過したため、再度ログインが必要です」とメッセージが出ます

**Comment by aprisun** [comment]
既存のcache が残っていて邪魔しているようだよ。

**Comment by aprisun** [comment]
Timeout value will be changed.

**Comment by aprisun** [comment]
timeout value changed.
