### ISSUE TITLE
画像サイズチェックのエラーメッセージがわかりにくい

### ISSUE THREAD

**Issue by yamamotoAIIT** [2016chubachi/tabitomo#204]
日本語でログインしてて下記のメッセージが出る。
Member member picture uploaded imagetoo_big_image

国際化して、かつ、upload可能なサイズを表示した方がよい

**Comment by aprisun** [comment]
def check_image
      if self.image
        if self.image.size > 2048.kilobytes
          errors.add(:uploaded_image, :too_large)
        end
        unless IMAGE_TYPES.has_key?(pictype)
          errors.add(:uploaded_image, :invalid_format)
        end
      end
    end

の部分だけど、
下記にしたら絵のメッセージが出るけど、解決方法知ってる。

en:
  activerecord:
    models:
      member_picture:
    attributes:
      member_picture:
        _destroy: "Destroy"
    errors:
      models:
        member_picture:
          attributes:
            uploaded_image:
              too_large: "Upload image size is too large. Please select less than 2Mb image."
              invalid_format: "Upload image type is invalid. Please upload jpg image type. "

![screen shot 2016-12-18 at 11 57 26 pm](https://cloud.githubusercontent.com/assets/9713934/21294362/f1e8667a-c57d-11e6-8bae-955326d72cae.png)

**Comment by aprisun** [comment]
Member member picture uploaded image　を消せる方法って知ってる。

**Comment by takeshitou** [comment]
逃げるようにした
