### ISSUE TITLE
ユーザーレビューの国際化に問題あり。

### ISSUE THREAD

**Issue by aprisun** [2016chubachi/tabitomo#205]
なぜか、ユーザーレビューが日本語になるので確認します。

**Comment by aprisun** [comment]
![screen shot 2016-12-18 at 10 48 10 pm](https://cloud.githubusercontent.com/assets/9713934/21293910/29288ad4-c574-11e6-8436-5a7c8c0fc1ef.png)

**Comment by aprisun** [comment]
page header の国際化をお願いします。

**Comment by yamamotoAIIT** [comment]
#207 左記のpull request で対応
