### ISSUE TITLE
Guideのプロフィールメンテ時のエラーとなると入力した値が消える

### ISSUE THREAD

**Issue by yamamotoAIIT** [2016chubachi/tabitomo#217]
@takeshitou さん　確認お願いします

画像サイズエラー時がでると、それまで入力していたその他の項目まで初期化されてしまうので、不便。入力した値は残して欲しい

**Comment by yamamotoAIIT** [comment]
redirect_to edit_guide_path @guide ではなくて、render "edit"にするとエラーは消えないようです

**Comment by takeshitou** [comment]
修正しました
