### ISSUE TITLE
予約画面でエラーになると日程をクリックしてもカレンダーが出ない

### ISSUE THREAD

**Issue by yamamotoAIIT** [2016chubachi/tabitomo#222]
@takeshitou さん　確認お願い

予約画面でエラーになると日程をクリックしてもカレンダーが出ない。

**Comment by takeshitou** [comment]
@yamamotoAIIT さん、
エラーでどのようなエラーですか、再現の仕方教えてください。

**Comment by yamamotoAIIT** [comment]
@takeshitou さん
再現する状況を添付ファイルにまとめました。確認をお願いします。
[issue_222.xlsx](https://github.com/2016chubachi/tabitomo/files/672836/issue_222.xlsx)

**Comment by takeshitou** [comment]
対応済み
