### ISSUE TITLE
information の件数

### ISSUE THREAD

**Issue by aprisun** [2016chubachi/tabitomo#226]
information で 何件がありますという文を削除してほしい。紛らわしいとユーザーは認識している。

**Comment by aprisun** [comment]
![screenshot from 2016-12-23 13-16-23](https://cloud.githubusercontent.com/assets/9713934/21447062/165a15f2-c912-11e6-832f-1a632c78898a.png)

**Comment by takeshitou** [comment]
削除したら、件数だけになちゃって。もっと分かりにくいと思う

**Comment by aprisun** [comment]
message だけを表示するようにする。

例：
１件のメッセージがあります。　このようなメッセージを出さない。

**Comment by aprisun** [comment]
修正予定なのでクローズ
