### ISSUE TITLE
レイアウト変更後の画面で言語を切り替えると写真が表示されない

### ISSUE THREAD

**Issue by yamamotoAIIT** [2016chubachi/tabitomo#239]
@takeshitouさん、 @shaoriさん　確認お願いします
 
レイアウト変更後の画面で言語を切り替えると写真が表示されない
http://tabitomo.herokuapp.com/en/

こっちは表示される
http://tabitomo.herokuapp.com

**Comment by takeshitou** [comment]
対応済み
